### ISSUE TITLE
Project One

### ISSUE THREAD

**Issue by lzawadowicz1** [kellymarieod/Project-1-Profile-Images#7]
(I apologize if I come off as nit-picky.)

~ The spacing to the left and to the right of the space flowers is not even. It seems that the group may be justified left but its so close to being centered that you might want to consider centering the row on the page.
~ I really, really love how the bottom of the page lines up with the picture of the shack on the moon but at the same time, it jumps out to me to be extremely similar but off. I think perhaps the moon texture on the bottom has slightly more yellow in it and its catching my attention in a weird way. You could perhaps put both files n Photoshop and adjust the color so they blend better. 

~ The font comes across as a bit difficult to read. I think the font you selected is good for headers and small groups of text but for a large body of text, you might want to try a simpler text.

~ Over all, I really like the look and the concept. Its really creative :)

**Comment by kellymarieod** [comment]
Thanks! Altered flower spacing.
